# Generated by Django 3.2.5 on 2021-07-16 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('sku', models.CharField(help_text='Enter Stock Keeping Unit', max_length=13)),
                ('name', models.CharField(help_text='Enter product name', max_length=200)),
                ('description', models.TextField(help_text='Enter product description')),
                ('buyPrice', models.DecimalField(decimal_places=2, help_text='Enter product price per unit', max_digits=20)),
                ('quantity', models.DecimalField(decimal_places=1, help_text='Enter quantity', max_digits=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
