# Generated by Django 3.2.5 on 2021-07-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Enter Stock Keeping Unit', max_length=13),
        ),
    ]
